#!/usr/bin/env node
/**
 * Generate .env and .env.local for developing directly in the carbon/ template.
 *
 * Uses the same hardcoded dev values as generate-dev-configs.sh
 * so everything works out of the box without running `vibecarbon create`.
 *
 * Usage:
 *   node scripts/dev-init.js           # Generate if missing
 *   node scripts/dev-init.js --force   # Overwrite existing files
 */

import { createHmac } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const force = process.argv.includes('--force');

// Dev values matching generate-dev-configs.sh.
// Note: ANON_KEY / SERVICE_ROLE_KEY are NOT hardcoded here — they're
// signed at runtime against JWT_SECRET below. Committing literal JWT
// strings tripped GitHub's secret-scanner on every push; signing on
// the fly keeps the dev workflow deterministic without leaking
// service-role-shaped values into git history.
const DEV = {
  PROJECT_NAME: 'vibecarbon',
  JWT_SECRET: 'local-dev-jwt-secret-must-be-at-least-32-chars-padded-padded',
  DB_ENC_KEY: 'devdbencryptkey1',
  VAULT_ENC_KEY: 'local-vault-encryption-key-1234567890',
  REALTIME_SECRET: 'local-realtime-secret-pad',
  DB_PASSWORD: 'local-postgres-password-for-dev-only',
  ANON_KEY: signDevJwt('anon', 'local-dev-jwt-secret-must-be-at-least-32-chars-padded-padded'),
  SERVICE_ROLE_KEY: signDevJwt(
    'service_role',
    'local-dev-jwt-secret-must-be-at-least-32-chars-padded-padded',
  ),
  ADMIN_EMAIL: 'admin@example.com',
  ADMIN_PASSWORD: 'local-admin-password',
};

function signDevJwt(role, secret) {
  const b64url = (buf) =>
    Buffer.from(buf)
      .toString('base64')
      .replace(/=+$/, '')
      .replace(/\+/g, '-')
      .replace(/\//g, '_');
  const header = b64url(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const payload = b64url(
    JSON.stringify({
      iss: 'supabase-demo',
      role,
      exp: Math.floor(Date.now() / 1000) + 100 * 365 * 24 * 60 * 60,
    }),
  );
  const sig = b64url(createHmac('sha256', secret).update(`${header}.${payload}`).digest());
  return `${header}.${payload}.${sig}`;
}

const envContent = `# =============================================================================
# DEV ENVIRONMENT - Generated by \`npm run dev:init\`
# Matches hardcoded values in generate-dev-configs.sh
# DO NOT COMMIT THIS FILE
# =============================================================================

# Project
PROJECT_NAME="${DEV.PROJECT_NAME}"
VITE_PROJECT_NAME="${DEV.PROJECT_NAME}"

# Supabase URLs (base ports — DEV_PORT_OFFSET is applied dynamically at runtime
# by src/server/lib/env.ts and vite.config.ts, so these stay at default 8000)
SUPABASE_URL="http://localhost:8000"
VITE_SUPABASE_URL="http://localhost:8000"

# Supabase Keys (standard Supabase demo keys)
SUPABASE_ANON_KEY="${DEV.ANON_KEY}"
VITE_SUPABASE_ANON_KEY="${DEV.ANON_KEY}"
SUPABASE_SERVICE_ROLE_KEY="${DEV.SERVICE_ROLE_KEY}"

# JWT Secret
JWT_SECRET="${DEV.JWT_SECRET}"

# Database
DB_PASSWORD="${DEV.DB_PASSWORD}"
POSTGRES_PASSWORD="${DEV.DB_PASSWORD}"

# Encryption keys (DB_ENC_KEY must be exactly 16 bytes for Realtime AES-128-ECB)
DB_ENC_KEY="${DEV.DB_ENC_KEY}"
VAULT_ENC_KEY="${DEV.VAULT_ENC_KEY}"
REALTIME_SECRET="${DEV.REALTIME_SECRET}"

# Admin credentials (matches super-admin.dev.sql)
ADMIN_EMAIL="${DEV.ADMIN_EMAIL}"
ADMIN_PASSWORD="${DEV.ADMIN_PASSWORD}"

# Site URL (base port — offset applied dynamically, see above)
SITE_URL="http://localhost:5173"

# Public URL — substituted into index.html's og:/twitter: meta tags by Vite's
# %VITE_PUBLIC_URL% replacement. Must be defined or Vite warns on every reload.
VITE_PUBLIC_URL="http://localhost:5173"

# OAuth (disabled for dev)
GOOGLE_ENABLED="false"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

MICROSOFT_ENABLED="false"
MICROSOFT_CLIENT_ID=""
MICROSOFT_CLIENT_SECRET=""
MICROSOFT_TENANT_ID=""

# External services (disabled for dev)
STRIPE_SECRET_KEY=""
STRIPE_WEBHOOK_SECRET=""
SMTP_HOST=""
SMTP_PORT="587"
SMTP_USER=""
SMTP_PASS=""
# SMTP_ADMIN_EMAIL=""
SMTP_SENDER_NAME="${DEV.PROJECT_NAME}"

# Optional services
VITE_N8N_ENABLED="false"
VITE_OBSERVABILITY_ENABLED="false"

# Analytics (Plausible - leave empty to disable)
VITE_PLAUSIBLE_DOMAIN=""
VITE_PLAUSIBLE_SCRIPT_URL=""

# Observability
GRAFANA_ADMIN_USER="admin"
GRAFANA_ADMIN_PASSWORD="admin"

# Ports
DEV_PORT_OFFSET="0"

# Environment
NODE_ENV="development"
PORT="3000"
VITE_ENVIRONMENT="development"
VITE_APP_VERSION="0.1.0"
`;

function writeEnv(filename) {
  if (existsSync(filename) && !force) {
    console.log(`  SKIP: ${filename} (exists, use --force to overwrite)`);
    return false;
  }
  writeFileSync(filename, envContent, { mode: 0o600 });
  console.log(`  ${force && existsSync(filename) ? 'OVERWRITTEN' : 'CREATED'}: ${filename}`);
  return true;
}

console.log('');
console.log('  Generating dev environment files...');
console.log('');

const wrote1 = writeEnv('.env');
const wrote2 = writeEnv('.env.local');

// Generate super-admin SQL with real credentials from the dev template.
// The template has ADMIN_EMAIL and ADMIN_PASSWORD_HASH placeholders that
// `vibecarbon create` replaces for real projects. For local CLI development we
// generate a separate file so the template stays clean (tracked by git), plus a
// docker-compose override that mounts the generated file into the db container.
// The hash is pre-computed for the fixed dev password — no bcrypt dependency needed.
const ADMIN_PASSWORD_HASH = '$2b$10$OWzZo/eSlFAb2S9oX4Ps5.prj7LzVfAWo7N1cFrL3N8Z3HLUZtvOm';
const sqlTemplatePath = 'volumes/db/super-admin.dev.sql';
const sqlGeneratedPath = 'volumes/db/super-admin.generated.sql';
if (existsSync(sqlTemplatePath)) {
  const sql = readFileSync(sqlTemplatePath, 'utf-8')
    .replace(/\{\{ADMIN_EMAIL\}\}/g, DEV.ADMIN_EMAIL)
    .replace(/\{\{ADMIN_PASSWORD_HASH\}\}/g, ADMIN_PASSWORD_HASH);
  writeFileSync(sqlGeneratedPath, sql);
  console.log(`  CREATED: ${sqlGeneratedPath} (dev admin credentials)`);

  // Write a compose override that mounts the generated SQL instead of the template.
  // Must target /tmp/super-admin.sql — that's the path `db:migrate` executes, and
  // docker-compose.override.yml mounts the raw template there. This file is loaded
  // after the override (getComposeFiles), so the same target wins and the seeded
  // admin gets real credentials instead of literal {{ADMIN_EMAIL}} placeholders.
  const composeOverride = `# Generated by dev-init.js — DO NOT COMMIT
services:
  db:
    volumes:
      - ./volumes/db/super-admin.generated.sql:/tmp/super-admin.sql:Z
`;
  writeFileSync('docker-compose.dev-init.yml', composeOverride);
  console.log('  CREATED: docker-compose.dev-init.yml (mounts generated admin SQL)');
}

console.log('');
if (wrote1 || wrote2) {
  console.log(`  Admin login: ${DEV.ADMIN_EMAIL} / ${DEV.ADMIN_PASSWORD}`);
  console.log('  Run `npm run dev:start` to start all services.');
} else {
  console.log('  No files written. Use --force to overwrite existing files.');
}
console.log('');
