/**
 * write-catalog — serializes a billing catalog snapshot into the project's
 * `src/shared/billing-catalog.ts` data module.
 *
 * The companion `billing-catalog.types.ts` ships in the template and is never
 * regenerated; this writer only replaces the data file so `vibecarbon
 * configure` (Billing → Stripe) can refresh pricing without touching types.
 */

import { existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Escaped TS string literal matching the repo's biome style: prefer single
 * quotes, but switch to double quotes when the string contains more single than
 * double quotes (biome's "fewer escapes" rule, e.g. `"Developer's Plan"`).
 */
function tsString(s) {
  const str = String(s);
  const singles = (str.match(/'/g) || []).length;
  const doubles = (str.match(/"/g) || []).length;
  const quote = singles > doubles ? '"' : "'";
  const escaped = str
    .replace(/\\/g, '\\\\')
    .replaceAll(quote, `\\${quote}`)
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `${quote}${escaped}${quote}`;
}

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const LINE_WIDTH = 80; // biome's default; keep generated output collapse/break-equivalent

function isPrimitive(v) {
  return v === null || typeof v === 'string' || typeof v === 'number' || typeof v === 'boolean';
}

/**
 * Serialize plain JSON-ish data (objects / strings / numbers / booleans / null)
 * into a biome-conformant TS object literal: unquoted identifier keys, single
 * quotes, trailing commas, two-space indent. Avoids the double-quoted, quoted-key
 * output of JSON.stringify, which fails the project's lint gate.
 *
 * `column` is the column at which this value begins, used to mirror biome's
 * "inline an array if it fits within the line width, else break one-per-line"
 * rule for primitive arrays (e.g. short `features` lists stay on one line).
 */
function serializeTs(value, indentLevel = 0, column = 0) {
  if (value === null) return 'null';
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (typeof value === 'string') return tsString(value);

  const pad = '  '.repeat(indentLevel);
  const padInner = '  '.repeat(indentLevel + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    if (value.every(isPrimitive)) {
      const inline = `[${value.map((v) => serializeTs(v)).join(', ')}]`;
      // +1 for the trailing comma that follows on the same line.
      if (column + inline.length + 1 <= LINE_WIDTH) return inline;
    }
    const items = value
      .map((v) => `${padInner}${serializeTs(v, indentLevel + 1, padInner.length)},`)
      .join('\n');
    return `[\n${items}\n${pad}]`;
  }

  const entries = Object.entries(value).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';
  const lines = entries
    .map(([k, v]) => {
      const key = IDENT_RE.test(k) ? k : tsString(k);
      const prefix = `${padInner}${key}: `;
      return `${prefix}${serializeTs(v, indentLevel + 1, prefix.length)},`;
    })
    .join('\n');
  return `{\n${lines}\n${pad}}`;
}

/**
 * Serialize + write the billing catalog into `<cwd>/src/shared/billing-catalog.ts`.
 *
 * The emitted module mirrors the shipped default's shape exactly: the
 * `import type { BillingCatalog }` line, a generated-file header, and
 * `export const billingCatalog: BillingCatalog = <json>;`.
 *
 * If `<cwd>/src/shared` does not exist this isn't an app project root — return
 * false and skip rather than throwing, so the configure flow never blocks on a
 * missing snapshot target.
 *
 * @param {string} cwd Project root.
 * @param {{ provider: string | null, generatedAt: string | null, tiers: Array<Record<string, unknown>> }} catalog
 *   `tiers` is a price-sorted list of activated products (CatalogTier[]).
 * @returns {boolean} true if written, false if skipped (no src/shared).
 */
export function writeBillingCatalog(cwd, catalog) {
  const sharedDir = join(cwd, 'src', 'shared');
  if (!existsSync(sharedDir)) return false;

  const targetPath = join(sharedDir, 'billing-catalog.ts');
  // Emit a biome-conformant TS literal (single quotes, unquoted keys, trailing
  // commas) so the generated file passes the project's lint gate as-is.
  const body = serializeTs(catalog, 0);

  const content = `/**
 * Billing catalog snapshot — GENERATED by \`vibecarbon configure\` (Billing →
 * Stripe). Do not hand-edit: re-run \`vibecarbon configure\` to refresh after
 * changing a price or product name in the provider dashboard, then redeploy.
 *
 * Contains NO secrets — product names, amounts, and price IDs are all public.
 * Types live in \`billing-catalog.types.ts\` (not regenerated).
 */

import type { BillingCatalog } from './billing-catalog.types';

export const billingCatalog: BillingCatalog = ${body};
`;

  writeFileSync(targetPath, content);
  return true;
}
