import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

/**
 * Regression guard for the `%VITE_PUBLIC_URL% is not defined` Vite warning.
 *
 * Vite substitutes `%VITE_*%` placeholders in index.html from the loaded env;
 * any placeholder with no matching env var warns on every (re)load. The dev
 * env is generated by `dev-init.js`, so every `%VITE_*%` placeholder in
 * index.html must be present in that generated env.
 */
const CARBON = join(process.cwd(), 'carbon');

describe('dev-init env covers every %VITE_*% placeholder in index.html', () => {
  let placeholders: string[];
  let envVars: Set<string>;
  let tmp: string;

  beforeAll(() => {
    const html = readFileSync(join(CARBON, 'src/client/index.html'), 'utf-8');
    placeholders = [...new Set([...html.matchAll(/%(VITE_[A-Z0-9_]+)%/g)].map((m) => m[1]))];

    // Generate the dev env exactly as `pnpm dev:init` does, in an isolated dir.
    tmp = mkdtempSync(join(tmpdir(), 'vc-devinit-'));
    execFileSync('node', [join(CARBON, 'scripts/dev-init.js'), '--force'], { cwd: tmp });
    const env = readFileSync(join(tmp, '.env'), 'utf-8');
    envVars = new Set([...env.matchAll(/^([A-Z0-9_]+)=/gm)].map((m) => m[1]));
  });

  afterAll(() => {
    if (tmp) rmSync(tmp, { recursive: true, force: true });
  });

  it('finds the placeholders it is meant to check', () => {
    // Sanity: index.html really does use %VITE_*% substitution.
    expect(placeholders).toContain('VITE_PUBLIC_URL');
  });

  it('defines every %VITE_*% placeholder used by index.html', () => {
    const missing = placeholders.filter((p) => !envVars.has(p));
    expect(missing, `dev env missing: ${missing.join(', ')}`).toEqual([]);
  });
});
