/**
 * Billing catalog snapshot — single source of truth for the operator's activated
 * provider products (the dynamic, price-sorted tier list).
 *
 * GENERATED by `vibecarbon configure` (Payments → Stripe): it fetches the live
 * products/prices, lets the operator pick which to activate, and writes them here
 * so the public pricing surface renders accurate pricing WITHOUT calling the
 * provider API on every page load. Re-run `vibecarbon configure` to refresh, then
 * redeploy.
 *
 * Contains NO secrets — product names, amounts, and price IDs are all public.
 * Ships empty; `pricing.ts` falls back to the generic free/starter/pro demo plans
 * until this is populated.
 *
 * Types live in `billing-catalog.types.ts` (not regenerated). Do not hand-edit
 * the data below — re-run `vibecarbon configure` instead.
 */

import type { BillingCatalog } from './billing-catalog.types';

export const billingCatalog: BillingCatalog = {
  provider: null,
  generatedAt: null,
  tiers: [],
};
