apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    app: vibecarbon-loki
    component: observability
spec:
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vibecarbon-loki
